sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: kzI8xKbguPkI1sBdyIu96ckPaetERMkj+pOaManIJPCWLJYJB9Rn5nuQ4OWSgl3BBodxC59fVxyJp5HxseGLfIXZ24ZhjYPRjZrvXYtaIMRveJ06I62btym6tUufwnbHeafIFewsV9qpOFQGyve2rzS5a1874QXbq2Wxwf7dCcfSQ13pyzU1ekXSq5FQvXNVyDdWu+hWkz1WekobATACkdMdA/AABOLB+rk77dQq85f38/QOcWH4KNg8nSmPgzm+IK+dguWCZhyUZPovRy7DRXOhDm8paAQZh05MNQxQD7hhvSL5d32QKWPylOqGEo2RF+/H37K56FgRqofSQWPqS6wgcitbXVh6e1wWospxMc94w2ndkwV/qh7SKa3NdWShCnfDNSmagpibUP2fIQJxqx+axHqDixnOMyW1ibTlt2h2XtUlqOeQkabJZjOX3sd8097APOkYyddnxEDLKEeo59xDjKPNvdWtGqeWt6ZPTMWBZXzMlYi7UqdjEwV/enXYl44KZGmrOuCh51vX2FcyIbdWIE8WvOJ3JNeBB5RoNzUroiqb7FRqM18DW7018xEq/oVDMx8n4IhXlX9I0XCHcElVbvgaPvL2xcUsJsgUtusW861UsJ2jAMMrDW1VvK+aHqECfW29SMS+vssrs6+ZdheqSuGe3jNZKcqP8iYABGo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Diary-of-Samuel-Pepys---Volume-35--May-June-1665_4156
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy